apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 16686
            - containerPort: 14250
            - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    app: opentelemetry
    component: otel-collector
  ports:
    - name: collector
      port: 4317
      protocol: TCP
      targetPort: 4317
  # ports:
  #   - name: collector
  #     port: 14250
  #     protocol: TCP
  #     targetPort: 14250
