# otel-collector-config.yml
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      otlp/jaeger:
        endpoint: jaeger-all-in-one:4317
        tls:
          insecure: true
      debug:
      logging:
        loglevel: debug
        sampling_initial: 1
        sampling_thereafter: 1
    processors:
      batch:
        send_batch_size: 1024
        timeout: 5s
      resource:
        attributes:
          - key: test.key
            value: "test-value"
            action: insert
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
      zpages:
        endpoint: :55679
    service:
      telemetry:
        logs:
          level: debug
      extensions: [zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/jaeger]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  type: LoadBalancer
  selector:
    component: otel-collector
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: zpages
      port: 55679
      protocol: TCP
      targetPort: 55679
    - name: health-check
      port: 13133
      protocol: TCP
      targetPort: 13133
    - name: jaeger
      port: 16686
      protocol: TCP
      targetPort: 16686
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      namespace: opentelemetry
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          image: otel/opentelemetry-collector:latest
          name: otel-collector
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 4317 #otlp grpc
            - containerPort: 4318 # otlp http
            - containerPort: 55679 # zpages
            - containerPort: 13133 # health check
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
